### PR TITLE
Make cube-powered cars unstoppable

### PR DESCRIPTION
**Pull request by Wiwiweb**
[11-01-2024 124543.webm](https://github.com/grandseiken/factorio-ultracube/assets/4723472/4b62bf5c-6b9f-443c-8d87-3b951bafcf8e)

Not sure if cube_fx was the best place to put the swapping code, but it was next to the ultralocomotion code so that seemed logical in some way. Feel free to move things around.

### CODE REVIEW

**Comment by grandseiken** [comment]
what do you think about adding a mod setting to enable this (I think this is hilarious, but could imagine people being annoyed by it as well)?

**Comment by Wiwiweb** [comment]
Ok, but how about default on? ;)

Just to clarify, you *can* brake and stop. I just went full throttle for the funny gif.

**Comment by grandseiken** [comment]
Yeah default on is fine

**Comment by grandseiken** [comment]
I'll merge this and add the setting.

**Pull request merged**
