### PR TITLE
Add default preset for the Milestones mod

### PR DESCRIPTION
**Pull request by Wiwiweb**
image

2 things related to the victory conditions are tracked as hidden milestones and not visible in the screenshot.

You'll notice that Resources group is a bit bare, because I haven't beaten your mod yet so I'm not sure what's considered a big milestone item or not. These are mostly my guesses from a brief perusing of the tech tree.
As the mod author you're the best placed to know what should be in this set, so please feel free to modify it in any way you want any time you want (this is the advantage of the remote interface).

### CODE REVIEW

**Comment by Wiwiweb** [comment]
After playing a bit more, I added stack inserters and loaders, and tweaked the Resources group a bit.

I noticed an issue with the "Cube" milestone. The cube is always marked as a catalyst in all recipes, so it only appears in production graphs when handcrafting and when burning it as a fuel, not for assembler recipes. The Milestones mod relies on production graphs, so that milestone is not so useful.

The `catalyst_amount` parameter does 2 things: 1) Removes the consumption/production of the item from the graphs, and 2) If applied on a product, this product will not be affected by productivity.

I noticed all recipes that involve the cube already don't accept productivity (except Resonance cascade). Therefore I think it should be safe to remove all `catalyst_amount` from cube ingredients/products (for Resonance cascade it could be left on the debris). 

I think even without Milestones it would be a plus, you could see how your cube consumption changed over time in the production graphs. But I didn't want to make that change before talking about it first.

**Comment by grandseiken** [comment]
this is cool! I might tweak things a bit, but it looks like a reasonable start.

About the cube recipes. You're right that currently cube recipes don't allow productivity modules, but this is not so much intentional design as just avoiding weird issues due to [this bug](https://forums.factorio.com/viewtopic.php?f=7&t=101436) (right now, if allowed, productivity modules mostly just make things worse by getting the cube stuck while the bonus outputs are dealt with). It'd be cool to count cube recipes, but I'd like to leave open the possibility of allowing productivity modules once that is fixed in 2.0.

I am not sure what happens if we remove the catalyst tag from cube ingredients only? Maybe that could allow counting the crafts while still avoiding bonus cubes if/when productivity modules get allowed.

**Comment by Wiwiweb** [comment]
> I might tweak things a bit, but it looks like a reasonable start.

Yes, please do. Even after this is released you can still change the preset, it will affect new games (And existing games but only if they choose to reload their preset).

> I am not sure what happens if we remove the catalyst tag from cube ingredients only?

It would be safe from productivity (only products matter for productivity). It would count the cube in consumption stats, but not add it (or a dormant cube) to production stats.

I can think of 2 ideas:

* You do this change and I will update Milestones to support consumption milestones instead of just production milestones. This shouldn't be too hard, just there hasn't really been a need for it yet.

* We change the milestone to the dormant cube instead since that appears in production graphs as a result of burning the cube. Then the milestone becomes a tracker of burning the cube specifically (might be a bit too oddly specific).

**Comment by grandseiken** [comment]
Yeah I think the first option there sounds good. I can merge this without the cube stats and update to add cube consumption when milestones supports that.

**Comment by grandseiken** [comment]
I've merged the PR and removed the catalyst tag from cube ingredients. Let me know when Milestones supports consumption and I can re-enable the cube ones.

**Pull request merged**
